import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import BlockComponent from '../components/BlockComponent'
import CarouselComponent from '../components/CarouselComponent'
import HeaderComponent from '../components/HeaderComponent'
import MainComponent from '../components/MainComponent'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  // Стейт для задания фокуса при клике в основном блоке
  const [isPatientClicked, setIsPatientClicked] = useState<boolean>(false);
  // Стейт определяющий взрослого / ребенка в карусели
  const [isAdult, setIsAdult] = useState<boolean>(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Мир Врача - Тестовое задание</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <HeaderComponent/>
        <main>
          <MainComponent>
            <BlockComponent
              isAdultList
              setIsClicked={setIsPatientClicked}
              setIsAdult={setIsAdult}
            />
            <BlockComponent
              isAdultList={false}
              setIsClicked={setIsPatientClicked}
              setIsAdult={setIsAdult}
            />
          </MainComponent>
          <CarouselComponent
            isClicked={isPatientClicked}
            setIsClicked={setIsPatientClicked}
            isAdult={isAdult}
          />
        </main>
      </div>
    </div>
  )
}

export default Home
